### ISSUE TITLE
Settings tab duplicate toggle

### ISSUE THREAD

**Issue by gapmiss** [iamrecursion/obsidian-pkvs#1]
Greetings~

If you open the PKVS settings tab more than once, you get duplicate toggles each time the settings tab is opened.

![CleanShot-Obsidian-Untitled - Playground - Obsidian v1 5 3-2024-01-26-05 57 31](https://github.com/iamrecursion/obsidian-pkvs/assets/98914514/0cf64821-69c1-4d0b-9a79-a5c42659e690)

The fix:

```diff
  display(): void {
    const { containerEl } = this;
+    containerEl.empty();

    new Setting(containerEl)
      .setName("Lazy Persistence")
```

**Comment by iamrecursion** [comment]
Thanks for the heads up! Fixed in [1.0.3](https://github.com/iamrecursion/obsidian-pkvs/releases/tag/1.0.3).
