### ISSUE TITLE
Observations around the plugin

### ISSUE THREAD

**Issue by 1C0D** [iamrecursion/obsidian-pkvs#2]
I was taking a look at this persistence plugin and had some thoughts around it

Attaching the data store directly to the window means serializing stuff to strings which is extra work. Why not use localStorage instead? That way you can just save the data as plain JSON without all the serialization.
LocalStorage would handle persisting between sessions. 
I think the save on exit would be maybe easier with an async function and a timer (but no guaranty). 
I don't know if it's 100% pertinent, but just sharing

**Comment by iamrecursion** [comment]
Thanks so much for your thoughts!

> Attaching the data store directly to the window means serializing stuff to strings which is extra work. 

Attaching it to the window isn't why we need to serialize to strings. That is a fundamental requirement of being able to store things that are more than standard JSON to disk as part of the plugin's `data.json`.

> Why not use localStorage instead? That way you can just save the data as plain JSON without all the serialization. LocalStorage would handle persisting between sessions. 

It would, but that LocalStorage would not sync between clients using Obsidian sync (or git/dropbox/iCloud Drive/etc). One big part of this is not only to persist between sessions, but between _devices_ with the same vault. 

> I think the save on exit would be maybe easier with an async function and a timer.

This would almost certainly _help_, but it doesn't solve the problem of potential data loss.
