### ISSUE TITLE
Fail to enable plugin on Android

### ISSUE THREAD

**Issue by azaol-aegnor** [iamrecursion/obsidian-pkvs#4]
Hello!

I first added the plugin via the Browse "shop". It installed the version 1.0.3. Trying to enable the plugin, I got the following error into the console.

```js
app.js:1 
 Plugin failure: pkvs TypeError: Cannot read properties of undefined (reading 'Buffer')
    at node_modules/safe-buffer/index.js (plugin:pkvs:47:26)
    at __require (plugin:pkvs:15:50)
    at node_modules/randombytes/browser.js (plugin:pkvs:110:19)
    at __require (plugin:pkvs:15:50)
    at node_modules/serialize-javascript/index.js (plugin:pkvs:144:23)
    at __require (plugin:pkvs:15:50)
    at anonymous (plugin:pkvs:334:43)
    at e.<anonymous> (app.js:1:2028752)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
```

Then, I removed the plugin and installed it using BRAT. Got the version 1.1.0 this time and enabling the plugin yields the exact same error, only at different lines.

```js
Plugin failure: pkvs TypeError: Cannot read properties of undefined (reading 'Buffer')
    at node_modules/safe-buffer/index.js (plugin:pkvs:10652:26)
    at __require (plugin:pkvs:15:50)
    at node_modules/randombytes/browser.js (plugin:pkvs:10715:19)
    at __require (plugin:pkvs:15:50)
    at node_modules/serialize-javascript/index.js (plugin:pkvs:10749:23)
    at __require (plugin:pkvs:15:50)
    at anonymous (plugin:pkvs:32782:43)
    at e.<anonymous> (app.js:1:2028752)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
```

Problematic line on my side highlighted in red here:
```diff
 // node_modules/safe-buffer/index.js
 var require_safe_buffer = __commonJS({
   "node_modules/safe-buffer/index.js"(exports2, module2) {
     var buffer = require("buffer");
-    var Buffer2 = buffer.Buffer;
     function copyProps(src, dst) {
       for (var key in src) {
         dst[key] = src[key];
       }
     }
```

Let me know if I can provide additional info to help troubleshoot!

**Comment by I-Pch** [comment]
I have a similar issue on iPadOS... 
 
I was able to install pkvs (1.1.0) from the `Community plugins` section on iPad (Obsidian 1.5.12 (134)) but I can't enable it 🤔 (each time I try, I get a `Failed to load pkvs` error)

(Seems to be working fine on Mac + Obsidian 1.5.12 though)

**Comment by iamrecursion** [comment]
Interesting! Cheers for the info; I'll take a look at some point today.

**Comment by iamrecursion** [comment]
This should be fixed now as of [1.1.1](https://github.com/iamrecursion/obsidian-pkvs/releases/tag/1.1.1). It only ever worked on my devices due to a non-standard set of developer flags, but this should work regardless now. Please let me know if there are any further problems after updating!

**Comment by azaol-aegnor** [comment]
It works!! Super happy to finally have a dev console on mobile!
Thank you so much and very well played on such a fast support!

*I'm closing this request as I opened it for Android and I leave the job to comment here or open another request to iOS device owners (if need be).*

**Comment by iamrecursion** [comment]
My tests were on iOS, so I hope it should now work there too!

I'm glad you'll get some use out of this, even if the dev tools are a bit of an add-on to the real purpose of this plugin!

**Comment by I-Pch** [comment]
Can confirm that the update fixed the issue on iPad too 😁 !

Thank you so very much for the quick fix Iamrecursion 🙌 !!!

**Comment by azaol-aegnor** [comment]
I will definitely get **some** use out of the dev tools as well as **_some_** use of the PKVS plugin! This, with MetaBind, allows me to throw my own plugin out the window.

I had mixed feelings about publicating it, as it was a lot of work already just for myself and some relatives, but after helping them migrate and migrating myself to this new combo, I won't have to maintain mine anymore!

**Comment by iamrecursion** [comment]
Awesome to have the iOS fix confirmation as well!
